version: "3.9"

services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: masot
      POSTGRES_USER: masot_user
      POSTGRES_PASSWORD: masot_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  backend:
    build:
      context: ./apps/backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - NEWS_API_KEY=${NEWS_API_KEY}
      - TICKETMASTER_API_KEY=${TICKETMASTER_API_KEY}
      - DATABASE_URL=postgresql://masot_user:masot_password@postgres:5432/masot
    volumes:
      - ./apps/backend:/app
    depends_on:
      - postgres
    restart: unless-stopped

  frontend:
    build:
      context: ./apps/frontend
      dockerfile: Dockerfile
    depends_on:
      - backend
    ports:
      - "3000:3000"
    environment:
      - VITE_BACKEND_URL=http://backend:8000
    volumes:
      - ./apps/frontend:/app
      - /app/node_modules
    restart: unless-stopped

volumes:
  postgres_data: