version: "3.9"

services:
  nginx:
    image: nginx:1.25-alpine
    ports:
      - "80:80"
      # - "443:443" # Uncomment if you set up SSL
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
      - frontend
    restart: always

  postgres:
    image: postgres:15-alpine
    environment:
      # These will be loaded from a .env file on your VM
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  backend:
    build:
      context: ./apps/backend
    environment:
      - DATABASE_URL=postgresql://${DB_USER}:${DB_PASSWORD}@postgres:5432/${DB_NAME}
      - SECRET_KEY=${SECRET_KEY}
    depends_on:
      - postgres
    restart: always

  frontend:
    build:
      context: ./apps/frontend
    environment:
      # This is a PRIVATE env var for the SvelteKit server proxy
      - BACKEND_URL=http://backend:8000
      - HOST=0.0.0.0
      - PORT=3000
    restart: always

volumes:
  postgres_data:
    # This ensures the volume is created and managed by Docker