version: "3.9"

services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: masot_db
      POSTGRES_USER: masot_user
      POSTGRES_PASSWORD: masot_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  backend:
    build:
      context: ./apps/backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://masot_user:masot_password@postgres:5432/masot_db
      - SECRET_KEY=your-local-dev-secret-key
    volumes:
      - ./apps/backend:/app
    depends_on:
      - postgres
    restart: unless-stopped

  frontend:
    build:
      context: ./apps/frontend
    ports:
      - "3000:3000"
    environment:
      - VITE_BACKEND_URL=http://localhost:8000
    volumes:
      - ./apps/frontend:/app
      # This prevents the local node_modules from overwriting the container's
      - /app/node_modules
    restart: unless-stopped

volumes:
  postgres_data: