# render.yaml
# This file configures the deployment of the services on Render.

databases:
  # 1. PostgreSQL Database
  - name: masot-postgres
    # The following are example values. Adjust them as needed.
    # See https://render.com/docs/yaml-spec#databases
    plan: free # 'starter' is a good paid option
    region: oregon
    # ipAllowList: [] # Allow all IPs to connect. For security, it's better to limit this.

services:
  # 2. FastAPI Backend Service
  - type: web
    name: masot-backend
    runtime: python
    region: oregon
    plan: free
    # Tell Render where the backend code is located
    rootDir: ./apps/backend
    # Commands to build and run the service
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port $PORT"
    healthCheckPath: "/"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      # Reference the database connection string from the postgres service
      - key: DATABASE_URL
        fromDatabase:
          name: masot-postgres
          property: connectionString
      # Link to the environment group defined below
      - fromGroup: masot-secrets

  # 3. SvelteKit Frontend Service
  - type: web
    name: masot-frontend
    runtime: node
    region: oregon
    plan: free
    # Tell Render where the frontend code is located
    rootDir: ./apps/frontend
    # Commands to build and run the service
    buildCommand: "npm install && npm run build"
    startCommand: "npm start"
    healthCheckPath: "/"
    envVars:
      - key: NODE_VERSION
        value: 18
      # Reference the backend URL from the backend service
      - key: VITE_BACKEND_URL
        fromService:
          type: web
          name: masot-backend
          property: hostport
      # SvelteKit adapter-node requires HOST. It will use the PORT env var provided by Render.
      - key: HOST
        value: "0.0.0.0"

# Environment Groups
# Define secret groups that can be shared across services.
# See https://render.com/docs/yaml-spec#environment-groups
envVarGroups:
  - name: masot-secrets
    envVars:
      - key: SECRET_KEY
        generateValue: true # Render will generate a secure, random value 